### ISSUE TITLE
Transmission parents

### ISSUE THREAD

**Issue by Sbenslimaneadanero** [criteo/addressable-network-proposals#30]
https://github.com/criteo/addressable-network-proposals/blob/e131a358f40c4d4bb3e0ae863d2c3132fc6237bd/mvp-spec/dsp-api.md?plain=1#L276
I think there is an inconsistency between the example here and the descriptions above @RomainLofaso .
Here the source object corresponds to the one from the receiver whereas in the Transmission Result Object description, you mentioned that the source is the one from the sender. 
In the case source object --> sender, how come the sender of the transmission request in this example could already be part of the transmission parents chain? 
In the case source object --> receiver, how can the publisher be a receiver as it is usually the root party originating the seed?
Might be useful to specify the transmissions chain of this example (publisher > ssp1 > ...)

**Comment by RomainLofaso** [comment]
Thank you. True, the source is actually the Receiver of the given Transmission Result, and therefore the Publisher doesn't have an associated Transmission Result.

Here is the fix: https://github.com/criteo/addressable-network-proposals/pull/37
