### ISSUE TITLE
Transmission response in case of "No bid"

### ISSUE THREAD

**Issue by Sbenslimaneadanero** [criteo/addressable-network-proposals#31]
https://github.com/criteo/addressable-network-proposals/blob/e131a358f40c4d4bb3e0ae863d2c3132fc6237bd/mvp-spec/dsp-api.md?plain=1#L483

Not sure to understand how we are going to handle the case where there is no bid for a specific impression. How will we pass the transmission response?

**Comment by RomainLofaso** [comment]
Thank you. We get also this feedback from the Iponweb team. We need to refine it. Here is a pull request for relaxing the requirements: https://github.com/criteo/addressable-network-proposals/pull/36

If you are fine with this, we merge this pull request, and then we can close this issue.

**Comment by Sbenslimaneadanero** [comment]
I added a comment directly in the pull request.
