### ISSUE TITLE
Clarify when signatures are verified

### ISSUE THREAD

**Issue by OlivierChirouze** [criteo/addressable-network-proposals#34]
I think it is agreed that signatures will be provided (one way or another):
- when an id is generated
- when a preferences value is saved
- (most likely) when messages are sent between operators and their clients
- when transmissions are sent as part of a bid request

We should clarify in the documentation **when these signatures are verified**, either as an optional or mandatory step.

For example, I have in mind that:
- all messages received by the operator **must** be verified
- all messages sent by the operator **must** be verified
- when id or preferences are to be written as a cookie on the operator domain, their signatures **must** be verified
- same thing on a website domain => I would recommend making it is also mandatory, but this is debatable
- in transmission, there is no need to verify transmission signatures except after the fact when audit log is requested
- however, should the preferences signature be verified before being used? probably not, if it has been done by the website

**Comment by RomainLofaso** [comment]
I think that it is important to note that there are two types of signatures:
1. Signature of the Prebid SSO data
2. Signature of the request.

A concrete example with both types is in the Operator API below. Even if what you have in mind can include it. I think that it is good to state that every signature of requests must be verified. 

*Request*
```
GET /v1/id-prefs?sender=advertiserA.com&timestamp=1639057962145&signature=message_signature_xyz1234
```
*Response*
```
{
  "sender": "operatorO.com",
  "timestamp": 1639059692793,
  "signature": "message_signature_xyz1234",
  "body": {
    "identifiers": [
      {
        "version": 1,
        "type": "prebid_id",
        "value": "560cead0-eed5-4d3f-a308-b818b4827979",
        "source": {
          "domain": "operator0.com",
          "timestamp": 1639643110,
          "signature": "prebid_id_signature_xyz12345"
        }
      }
    ]
  }
}
```

In this sense, for your 4th point, I think that we don't need to verify the signature of the Prebid SSO data. Indeed, in the case of a redirect, we already verify the identity of the Operator with the signature of the request. In the case of a 3PC (i.e direct call), we can rely on HTTPS to avoid any middleman.

Agree with the rest.

**Comment by OlivierChirouze** [comment]
Added "signature" document in https://github.com/criteo/addressable-network-proposals/pull/67
It does not answer the question "when to verify", but goes into a simplification of the doc, I hope.
Next step is to update other docs to clarify when signatures are verified.

**Comment by OlivierChirouze** [comment]
Clarified when signatures must be verified (for the "id and prefs" scope) in https://github.com/criteo/addressable-network-proposals/pull/68

**Comment by OlivierChirouze** [comment]
@RomainLofaso do you think we can close this issue now?
I believe with the latest PR it is ok.
