### ISSUE TITLE
1PC check in advertiser use case

### ISSUE THREAD

**Issue by Sbenslimaneadanero** [criteo/addressable-network-proposals#39]
https://github.com/criteo/addressable-network-proposals/blob/d0c18b9a4c5b516ddb7d215b6a44a40ac78f3444/mvp-spec/operator-requirements.md?plain=1#L298

Should this not happen on the browser layer? Why is it happening on the advertiser side here while for the publisher it's happening on the browser?

**Comment by OlivierChirouze** [comment]
This is not clear in the diagram or in the text, indeed.

In this case, the assumption is that the publisher is not using an operator **backend client** but only the **frontend** library.

- If the publisher would also have a backend client, then it would be detected at the backend level.
- If the advertiser would not have the backend client, then it would be detected only at the frontend level (in the browser, I mean).

I will update the doc to make this assumption more clear and let you close the issue if you think this is enough.

Thanks

**Comment by Sbenslimaneadanero** [comment]
Ok I better understand now. How can I see the updates related to this issue? (I'm still ramping-up on Github... and getting lost from time to time)

**Comment by OlivierChirouze** [comment]
Right here on this page, you will notice that after my previous comment (3 days ago), there is an automatic line mentioning that I "added a commit that referenced this issue".
If you click on the link below (`Rephrase operator design & requirements`), you will be taken to the related changes.
