### ISSUE TITLE
Generate Mermaid images automatically

### ISSUE THREAD

**Issue by OlivierChirouze** [criteo/addressable-network-proposals#46]
As we discussed earlier, we need to make the Mermaid diagrams visible to anyone, without the need for a browser plugin.

This could be through:
- automatic generation of svg or png image through https://github.com/mermaid-js/mermaid-cli
- extension of the existing "partials" scripts created in https://github.com/criteo/addressable-network-proposals/commit/4e25e62b65e93abf0b936bafa1c45a2a40b62b72

We could also use GitHub actions to generate the files (ex: https://nielsvaneck.com/post/2021-01-31-render-md-mermaid-a-github-action/) but that would mean creating an extra commit each time

**Comment by RomainLofaso** [comment]
Maybe we should consider a templating system instead of the partial script if we had multiple feature like this one.

Else a solution should be to create an API in the partial updater like this:
```
<!--partial-begin { "files": [ "my-mermaid.mmd" ], "transformation": "mermaid" } -->
<!-- ⚠️ GENERATED CONTENT - DO NOT MODIFY DIRECTLY ⚠️ -->
 ![My Mermaid](/assets/images/generated-my-mermaid.png)
<!--partial-end-->
```

**Comment by RomainLofaso** [comment]
Attached PR: https://github.com/criteo/addressable-network-proposals/pull/49

**Comment by OlivierChirouze** [comment]
👏
