### ISSUE TITLE
"human-readable" is confusing

### ISSUE THREAD

**Issue by broggeri** [criteo/addressable-network-proposals#53]
https://github.com/criteo/addressable-network-proposals/blob/29daf5631c703f51d26753856ea4cbd9fba462e5/mvp-spec/operator-design.md?plain=1#L7

2 minor issues on that line:

###  "Note that when using HTTPS, query string parameters are encrypted." 

I think it's better to remove this part. We already said that HTTPS is mandatory, and everybody knows HTTPS in an encrypted transport.
If we really want to highlight differences with SWAN, I would consider to create a separate document because it makes this one confusing for people non familiar with SWAN. 

###  "data is transferred in a human-readable fashion"

This makes it sound as if we're suggesting end users are supposed to inspect the request and responses.
What we really mean is that we'd like to be developer friendly.
Alternative suggestion:

"data is transferred in a text format [or: text protocol] to facilitate inspection and troubleshooting by web developers"

"human-readable" term is used a few other times in this document and maybe in other places in this repo.

**Comment by OlivierChirouze** [comment]
Thanks for the feedback, good point indeed.
I will rephrase to replace "human readable" with something more "developer oriented".
