### ISSUE TITLE
Should we use OpenRTB schain object ?

### ISSUE THREAD

**Issue by broggeri** [criteo/addressable-network-proposals#7]
https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/supplychainobject.md

"The SupplyChain Object enables buyers and intermediaries to see all parties who are selling or reselling ad inventory."

Sounds like we might map our audit transaction data into that existing spec.

**Comment by RomainLofaso** [comment]
After this discussion and an informal discussion with the Iponweb team, we will close this issue.  We exclude schain object for the short/middle term, but we may reconsider for the long term.
